name: server_controll
description: "MineControl - local Minecraft server controller"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  sqflite_common_ffi: ^2.3.6
  path: ^1.9.1
  path_provider: ^2.1.5
  intl: ^0.20.2
  file_picker: ^10.3.2
  sqlite3_flutter_libs: ^0.5.39
  archive: ^3.6.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "lib/assets/minecraft.png"
  windows:
    generate: true
    image_path: "lib/assets/minecraft.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "lib/assets/minecraft.png"
  linux:
    generate: true
    image_path: "lib/assets/minecraft.png"

