enum ServerPropertyFieldType { boolean, integer, string, enumeration }

class ServerPropertyFieldDefinition {
  const ServerPropertyFieldDefinition({
    required this.key,
    required this.label,
    required this.group,
    required this.type,
    required this.description,
    this.defaultValue = '',
    this.minValue,
    this.maxValue,
    this.options = const [],
  });

  final String key;
  final String label;
  final String group;
  final ServerPropertyFieldType type;
  final String description;
  final String defaultValue;
  final int? minValue;
  final int? maxValue;
  final List<String> options;
}

const serverPropertiesCatalog = <ServerPropertyFieldDefinition>[
  ServerPropertyFieldDefinition(
    key: 'motd',
    label: 'Descrição (MOTD)',
    group: 'Servidor',
    type: ServerPropertyFieldType.string,
    description: 'Mensagem exibida na lista de servidores.',
    defaultValue: 'A Minecraft Server',
  ),
  ServerPropertyFieldDefinition(
    key: 'max-players',
    label: 'Máximo de players',
    group: 'Servidor',
    type: ServerPropertyFieldType.integer,
    description: 'Define o número máximo de jogadores simultâneos.',
    defaultValue: '20',
    minValue: 1,
    maxValue: 1000,
  ),
  ServerPropertyFieldDefinition(
    key: 'gamemode',
    label: 'Modo de jogo padrão',
    group: 'Gameplay',
    type: ServerPropertyFieldType.enumeration,
    description: 'Modo inicial aplicado aos jogadores.',
    defaultValue: 'survival',
    options: ['survival', 'creative', 'adventure', 'spectator'],
  ),
  ServerPropertyFieldDefinition(
    key: 'hardcore',
    label: 'Hardcore',
    group: 'Gameplay',
    type: ServerPropertyFieldType.boolean,
    description: 'Ativa modo hardcore (morte com ban do mundo).',
    defaultValue: 'false',
  ),
  ServerPropertyFieldDefinition(
    key: 'pvp',
    label: 'PVP',
    group: 'Gameplay',
    type: ServerPropertyFieldType.boolean,
    description: 'Permite combate entre jogadores.',
    defaultValue: 'true',
  ),
  ServerPropertyFieldDefinition(
    key: 'difficulty',
    label: 'Dificuldade',
    group: 'Gameplay',
    type: ServerPropertyFieldType.enumeration,
    description: 'Define a dificuldade do servidor.',
    defaultValue: 'easy',
    options: ['peaceful', 'easy', 'normal', 'hard'],
  ),
  ServerPropertyFieldDefinition(
    key: 'allow-flight',
    label: 'Permitir voo',
    group: 'Gameplay',
    type: ServerPropertyFieldType.boolean,
    description: 'Permite voo no servidor sem kick automático.',
    defaultValue: 'false',
  ),
  ServerPropertyFieldDefinition(
    key: 'spawn-protection',
    label: 'Proteção de spawn',
    group: 'Gameplay',
    type: ServerPropertyFieldType.integer,
    description: 'Raio de proteção ao redor do spawn.',
    defaultValue: '16',
    minValue: 0,
    maxValue: 128,
  ),
  ServerPropertyFieldDefinition(
    key: 'allow-nether',
    label: 'Permitir Nether',
    group: 'Mundo',
    type: ServerPropertyFieldType.boolean,
    description: 'Habilita viagens para o Nether.',
    defaultValue: 'true',
  ),
  ServerPropertyFieldDefinition(
    key: 'level-name',
    label: 'Nome do mundo',
    group: 'Mundo',
    type: ServerPropertyFieldType.string,
    description: 'Pasta principal do mundo na raiz do servidor.',
    defaultValue: 'world',
  ),
  ServerPropertyFieldDefinition(
    key: 'level-seed',
    label: 'Seed do mundo',
    group: 'Mundo',
    type: ServerPropertyFieldType.string,
    description: 'Seed usada para gerar o mundo.',
    defaultValue: '',
  ),
  ServerPropertyFieldDefinition(
    key: 'level-type',
    label: 'Tipo de mundo',
    group: 'Mundo',
    type: ServerPropertyFieldType.string,
    description: 'Preset/tipo de geração do mundo.',
    defaultValue: 'minecraft:normal',
  ),
  ServerPropertyFieldDefinition(
    key: 'generate-structures',
    label: 'Gerar estruturas',
    group: 'Mundo',
    type: ServerPropertyFieldType.boolean,
    description: 'Ativa geração de estruturas no mundo.',
    defaultValue: 'true',
  ),
  ServerPropertyFieldDefinition(
    key: 'view-distance',
    label: 'View distance',
    group: 'Performance',
    type: ServerPropertyFieldType.integer,
    description: 'Distância de renderização de chunks.',
    defaultValue: '10',
    minValue: 2,
    maxValue: 32,
  ),
  ServerPropertyFieldDefinition(
    key: 'simulation-distance',
    label: 'Simulation distance',
    group: 'Performance',
    type: ServerPropertyFieldType.integer,
    description: 'Distância de simulação de entidades/chunks.',
    defaultValue: '10',
    minValue: 2,
    maxValue: 32,
  ),
  ServerPropertyFieldDefinition(
    key: 'network-compression-threshold',
    label: 'Compressão de rede',
    group: 'Rede',
    type: ServerPropertyFieldType.integer,
    description: 'Threshold em bytes para compressão de pacotes.',
    defaultValue: '256',
    minValue: -1,
    maxValue: 65535,
  ),
  ServerPropertyFieldDefinition(
    key: 'max-tick-time',
    label: 'Tempo máximo de tick',
    group: 'Performance',
    type: ServerPropertyFieldType.integer,
    description: 'Tempo em ms antes de watchdog encerrar o servidor.',
    defaultValue: '60000',
    minValue: -1,
    maxValue: 2147483647,
  ),
  ServerPropertyFieldDefinition(
    key: 'use-native-transport',
    label: 'Transporte nativo',
    group: 'Performance',
    type: ServerPropertyFieldType.boolean,
    description: 'Ativa otimizações nativas de rede.',
    defaultValue: 'true',
  ),
  ServerPropertyFieldDefinition(
    key: 'online-mode',
    label: 'Online mode',
    group: 'Segurança',
    type: ServerPropertyFieldType.boolean,
    description: 'Verifica autenticação oficial da Mojang/Microsoft.',
    defaultValue: 'true',
  ),
  ServerPropertyFieldDefinition(
    key: 'enforce-whitelist',
    label: 'Forçar whitelist',
    group: 'Segurança',
    type: ServerPropertyFieldType.boolean,
    description: 'Aplica whitelist para entrada de players.',
    defaultValue: 'false',
  ),
  ServerPropertyFieldDefinition(
    key: 'white-list',
    label: 'Whitelist',
    group: 'Segurança',
    type: ServerPropertyFieldType.boolean,
    description: 'Ativa a whitelist do servidor.',
    defaultValue: 'false',
  ),
  ServerPropertyFieldDefinition(
    key: 'enable-command-block',
    label: 'Command blocks',
    group: 'Segurança',
    type: ServerPropertyFieldType.boolean,
    description: 'Permite uso de command blocks no mundo.',
    defaultValue: 'false',
  ),
  ServerPropertyFieldDefinition(
    key: 'server-port',
    label: 'Porta do servidor',
    group: 'Rede',
    type: ServerPropertyFieldType.integer,
    description: 'Porta TCP para conexões de jogadores.',
    defaultValue: '25565',
    minValue: 1,
    maxValue: 65535,
  ),
  ServerPropertyFieldDefinition(
    key: 'server-ip',
    label: 'IP do servidor',
    group: 'Rede',
    type: ServerPropertyFieldType.string,
    description: 'IP de bind do servidor (vazio = automático).',
    defaultValue: '',
  ),
  ServerPropertyFieldDefinition(
    key: 'query.port',
    label: 'Query port',
    group: 'Rede',
    type: ServerPropertyFieldType.integer,
    description: 'Porta para protocolo query.',
    defaultValue: '25565',
    minValue: 1,
    maxValue: 65535,
  ),
  ServerPropertyFieldDefinition(
    key: 'rcon.port',
    label: 'RCON port',
    group: 'Rede',
    type: ServerPropertyFieldType.integer,
    description: 'Porta para administração remota via RCON.',
    defaultValue: '25575',
    minValue: 1,
    maxValue: 65535,
  ),
  ServerPropertyFieldDefinition(
    key: 'enable-rcon',
    label: 'Ativar RCON',
    group: 'Rede',
    type: ServerPropertyFieldType.boolean,
    description: 'Habilita administração remota RCON.',
    defaultValue: 'false',
  ),
];
